name: Unit Tests

on:
  pull_request:
    branches:
      - main
      - develop

env:
  HUSKY: 0

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - name: Code Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
